/*
** EPITECH PROJECT, 2020
** C_FUNCTIONS LIBRARY
** File description:
** C_FUNCTIONS MACROS
*/

#ifndef C_FUNCTIONS_MACROS_
#define C_FUNCTIONS_MACROS_

#define MIN_NUMBER 48
#define MAX_NUMBER 57
#define MIN_UPPER 65
#define MAX_UPPER 90
#define MIN_LOWER 97
#define MAX_LOWER 122
#define MIN_PRINTABLE 32
#define MAX_PRINTABLE 126

#endif /* !C_FUNCTIONS_MACROS_ */